#spring:
#  application:
#    name: authorization-service
#  cloud:
#    config:
#      enable: true
#      uri: http://localhost:8888
server:
  port: 9000
spring:
  application:
    name: authorization-service
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO