server:
  port: 8001
spring:
  h2:
    console:
      path: /h2-console
    settings:
      web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

