server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: git@github.com:Evaristo00/householdChores.git
          search-path: config-data
          ssh-key:
            privateKey: C:\Users\evari\.ssh\id_rsa
          clone-on-start: true
  application:
    name: config-server
