#server:
#  port: 8081
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          default-label: config-server
#          uri: git@github.com:Evaristo00/householdChores.git
#          search-path: config-data
#          ssh-key:
#            privateKey: C:\Users\evari\.ssh\id_rsa
#          clone-on-start: true
#  application:
#    name: config-service

spring.application.name=config-server
server.port=8081
spring.cloud.config.server.git.default-label=config-server
spring.cloud.config.server.git.uri=git@github.com:Pedro-Molina/EatFit.git
spring.cloud.config.server.git.search-paths=config-data
spring.cloud.config.server.git.ssh-key.privateKey=C:\Users\evari\.ssh\id_rsa
spring.cloud.config.server.git.