server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:Evaristo00/householdChores.git
          search-paths: config-data
          ssh-key:
            privateKey: C:\Users\evari\.ssh\id_rsa
  application:
    name: config-service
